### ISSUE TITLE
Segmentation fault in TransposeFasta.cpp

### ISSUE THREAD

**Issue by adlerenno** [giovannarosone/BCR_LCP_GSA#6]
Hi,

I have a Segmentation fault error in TransposeFasta.cpp where I don't know how to fix it or where it comes from. I used GDB to find out that it is related to line 566 in TransposeFasta.cpp.

I'm using the file at https://ftp.ncbi.nlm.nih.gov/1000genomes/ftp/pilot_data/data/NA06984/sequence_read/SRR006041.recal.fastq.gz as input file (called input.fastq) and I'm working on Linux 5.10.0-25-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux.

Thanks for the help in advance,
Best,
Enno

The console output (from the call gdb --args ./BCR_LCP_GSA input.fastq output.bwt):

Starting program: ./BCR_LCP_GSA input.fastq output.bwt
BWTCollection: The input is input.fastq
BWTCollection: The output is output.bwt
Compute the EBWT
The output format of BCR is at most 5 files (ebwt, lcp, da, posSA, SAP-array) at the same time.
BCR uses the external memory for the BWT partial
BCR of multi-sequences
Lexicographic order
dataTypedimAlpha: sizeof(type size of alpha): 1 bytes 
dataTypelenSeq: sizeof(type of seq length): 1 bytes 
dataTypeNSeq: sizeof(type of #sequences): 4 bytes
dataTypeNChar: sizeof(type of #sequences): 8 bytes
TIMER start buildBCR User: 1e-05s System: 0s Actual: 1.1e-05s Efficiency: 90.9091%

Builds cyc. files and the builds the BCR 
The  (new and-or old) reads have a different length.
Number of sequences reading/writing: 18357
Number of characters reading/writing: 3639911
In the new collection, we have: 
TrasposeFasta: init buf_ for bases of size 255 * 1048576

Program received signal SIGSEGV, Segmentation fault.
0x000055555555fd01 in TransposeFasta::convert (this=this@entry=0x7fffffffd950, 
    input="input.fastq", 
    fileOutput=fileOutput@entry=0x7fffffffe6bb "output.bwt", output="cyc.", 
    ram=ram@entry=17, BCRprefPrev="") at TransposeFasta.cpp:566
566

**Comment by giovannarosone** [comment]
Dear Enno,
the dataset SRR006041 seems to contain some reads of length >= 255, which is the maximum allowed if the type dataTypelenSeq is set by default.

Thanks for your message, I'll add a check in the code so that one can have a meaningful error message.

To run your instance, please modify the file Parameters.h so that the definition of dataTypeLengthSequences (https://github.com/giovannarosone/BCR_LCP_GSA/blob/15e81ec14f9faf8e7a56b4dabaca65b020b78f74/Parameters.h#L68) is 1 instead of 0. In this way, you are allowing a maximum read length of 65535.


Finally, note that BCR needs a number of iterations which depends on read length.

Giovanna

**Comment by adlerenno** [comment]
Dear Giovanna,

Thank you for your help. For some reason, the project wasn't proper recompiling the source files with the changed data types when I changed the definition in line 68. Either removing all object files (*.o) or cloning the project again from GitHub works for me.

Thank you for your help,
Enno
